import { BaseSeeder } from '@adonisjs/lucid/seeders'
import User from '#models/user'

export default class UserSeeder extends BaseSeeder {
  async run() {
    const userData = [
      {
        full_name: 'The Super Admin',
        email: 'admin@fichua.com',
        password: 'password',
        phone_number: '123456789022',
        role: 'admin',
        national_id: '123456789011',
      },
      {
        full_name: 'The Officer',
        email: 'officer@fichua.com',
        password: 'password',
        phone_number: '987654321330',
        role: 'officer',
        national_id: '098765444321',
      },
      {
        full_name: 'The User',
        email: 'user@gmail.com',
        password: 'password',
        phone_number: '555155234567',
        role: 'officer',
        national_id: '5555536633255555',
      },
      {
        full_name: 'Innocent Maina',
        email: 'innocentwahome@gmail.com',
        password: 'password',
        phone_number: '225155234567',
        role: 'admin',
        national_id: '533255555',
      },
      {
        full_name: 'John Doe',
        email: 'john@example.com',
        password: 'password123',
        phone_number: '1234567890',
        role: 'admin',
        national_id: '1234567890',
      },
      {
        full_name: 'Jane Smith',
        email: 'jane@example.com',
        password: 'pass123',
        phone_number: '9876543210',
        role: 'user',
        national_id: '0987654321',
      },
      {
        full_name: 'Alice Johnson',
        email: 'alice@example.com',
        password: 'alicepass',
        phone_number: '5551234567',
        role: 'officer',
        national_id: '55555333255555',
      },
      {
        full_name: 'Bob Brown',
        email: 'bob@example.com',
        password: 'bobpassword',
        phone_number: '4445556666',
        role: 'user',
        national_id: '4444322444444',
      },
      {
        full_name: 'Emma Watson',
        email: 'emma@example.com',
        password: 'emmapassword',
        phone_number: '3334445555',
        role: 'user',
        national_id: '333E323333333',
      },
      {
        full_name: 'Michael Johnson',
        email: 'michael@example.com',
        password: 'michaelpassword',
        phone_number: '2223334444',
        role: 'user',
        national_id: '2222232322222',
      },
      {
        full_name: 'Jessica Brown',
        email: 'jessica@example.com',
        password: 'jessicapassword',
        phone_number: '1112223333',
        role: 'user',
        national_id: '111111321111',
      },
      {
        full_name: 'Chris Evans',
        email: 'chris@example.com',
        password: 'chrispassword',
        phone_number: '999338887777',
        role: 'user',
        national_id: '9999211999999',
      },
      {
        full_name: 'Scarlett Johansson',
        email: 'scarlett@example.com',
        password: 'scarlettpassword',
        phone_number: '888774476666',
        role: 'officer',
        national_id: '32323245378',
      },
      {
        full_name: 'Ryan Reynolds',
        email: 'ryan@example.com',
        password: 'ryanpassword',
        phone_number: '77764343665555',
        role: 'officer',
        national_id: '7777434332777777',
      },
      {
        full_name: 'Angelina Jolie',
        email: 'angelina@example.com',
        password: 'angelinapassword',
        phone_number: '66643435554444',
        role: 'officer',
        national_id: '66666322266666',
      },
      {
        full_name: 'Brad Pitt',
        email: 'brad@example.com',
        password: 'bradpassword',
        phone_number: '555433443333',
        role: 'officer',
        national_id: '5555521555551',
      },
      {
        full_name: 'Jennifer Lawrence',
        email: 'jennifer@example.com',
        password: 'jenniferpassword',
        phone_number: '4443332222',
        role: 'user',
        national_id: '4444444444',
      },
      {
        full_name: 'Tom Cruise',
        email: 'tom@example.com',
        password: 'tompassword',
        phone_number: '3332221111',
        role: 'user',
        national_id: '3333333333',
      },
      {
        full_name: 'Megan Fox',
        email: 'megan@example.com',
        password: 'meganpassword',
        phone_number: '2221110000',
        role: 'officer',
        national_id: '2222222222',
      },
      {
        full_name: 'Will Smith',
        email: 'will@example.com',
        password: 'willpassword',
        phone_number: '1110009999',
        role: 'officer',
        national_id: '1111111111',
      },
      {
        full_name: 'Leonardo DiCaprio',
        email: 'leo@example.com',
        password: 'leopassword',
        phone_number: '0009998888',
        role: 'officer',
        national_id: '0000000000',
      },
      {
        full_name: 'Jennifer Aniston',
        email: 'jenniferaniston@example.com',
        password: 'jenniferanistonpassword',
        phone_number: '9998887777',
        role: 'officer',
        national_id: '9999999999',
      },
      {
        full_name: 'George Clooney',
        email: 'george@example.com',
        password: 'georgepassword',
        phone_number: '8887776666',
        role: 'user',
        national_id: '8888888888',
      },
      {
        full_name: 'Anne Hathaway',
        email: 'anne@example.com',
        password: 'annepassword',
        phone_number: '7776665555',
        role: 'user',
        national_id: '7777777777',
      },
      {
        full_name: 'Matthew McConaughey',
        email: 'matthew@example.com',
        password: 'matthewpassword',
        phone_number: '6665554444',
        role: 'user',
        national_id: '6666666666',
      },
      {
        full_name: 'Charlize Theron',
        email: 'charlize@example.com',
        password: 'charlizepassword',
        phone_number: '5554443333',
        role: 'user',
        national_id: '55555553555',
      },
    ]
    await User.createMany(userData)
  }
}
